version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '12200:12200'
    environment:
      PORT: 12200
      HOST: 0.0.0.0
    command: ['npm', 'run', 'start']
