version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '12200:12200'
    command: ["npm", "run", "develop", "--", "--host", "0.0.0.0", "--port", "12200"]
